// <auto-generated />
using LearnWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnWebApi.Data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20250819183700_createCustomerTable")]
    partial class createCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnWebApi.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LearnWebApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop Dell XPS 15",
                            Price = 45000000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bàn phím cơ Logitech G Pro",
                            Price = 3500000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chuột gaming Razer DeathAdder V2",
                            Price = 1800000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Màn hình cong Samsung Odyssey G9",
                            Price = 28000000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tai nghe chống ồn Sony WH-1000XM5",
                            Price = 8000000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ổ cứng SSD Samsung 980 Pro 1TB",
                            Price = 3200000m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Máy ảnh Fujifilm X-T5",
                            Price = 38000000m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ống kính Canon RF 50mm f/1.8",
                            Price = 6000000m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bếp điện từ Kangaroo KG499I",
                            Price = 1500000m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nồi chiên không dầu Philips HD9252/90",
                            Price = 2800000m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Robot hút bụi Xiaomi Robot Vacuum E10",
                            Price = 5500000m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tivi Sony Bravia 55 inch",
                            Price = 17500000m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Loa Bluetooth JBL Flip 6",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Máy lọc không khí Coway AP-1009CH",
                            Price = 4200000m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Đồng hồ thông minh Apple Watch Series 8",
                            Price = 12000000m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Giày thể thao Adidas Ultraboost 22",
                            Price = 3000000m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Áo khoác gió Uniqlo",
                            Price = 800000m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sách 'Đắc nhân tâm'",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Dầu gội đầu Rejoice",
                            Price = 85000m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bộ LEGO Technic Bugatti Chiron",
                            Price = 10500000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
